#line 2 "bconf.lex.c"

#line 4 "bconf.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer bconf_create_buffer
#define yy_delete_buffer bconf_delete_buffer
#define yy_flex_debug bconf_flex_debug
#define yy_init_buffer bconf_init_buffer
#define yy_flush_buffer bconf_flush_buffer
#define yy_load_buffer_state bconf_load_buffer_state
#define yy_switch_to_buffer bconf_switch_to_buffer
#define yyin bconfin
#define yyleng bconfleng
#define yylex bconflex
#define yylineno bconflineno
#define yyout bconfout
#define yyrestart bconfrestart
#define yytext bconftext
#define yywrap bconfwrap
#define yyalloc bconfalloc
#define yyrealloc bconfrealloc
#define yyfree bconffree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE bconfrestart(bconfin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int bconfleng;

extern FILE *bconfin, *bconfout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE bconflex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-bconflineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < bconfleng; ++yyl )\
                    if ( bconftext[yyl] == '\n' )\
                        --bconflineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up bconftext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up bconftext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via bconfrestart()), so that the user can continue scanning by
	 * just pointing bconfin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when bconftext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int bconfleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow bconfwrap()'s to do buffer switches
 * instead of setting up a fresh bconfin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void bconfrestart (FILE *input_file  );
void bconf_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE bconf_create_buffer (FILE *file,int size  );
void bconf_delete_buffer (YY_BUFFER_STATE b  );
void bconf_flush_buffer (YY_BUFFER_STATE b  );
void bconfpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void bconfpop_buffer_state (void );

static void bconfensure_buffer_stack (void );
static void bconf_load_buffer_state (void );
static void bconf_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER bconf_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE bconf_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE bconf_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE bconf_scan_bytes (yyconst char *bytes,int len  );

void *bconfalloc (yy_size_t  );
void *bconfrealloc (void *,yy_size_t  );
void bconffree (void *  );

#define yy_new_buffer bconf_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        bconfensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            bconf_create_buffer(bconfin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        bconfensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            bconf_create_buffer(bconfin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define bconfwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *bconfin = (FILE *) 0, *bconfout = (FILE *) 0;

typedef int yy_state_type;

extern int bconflineno;

int bconflineno = 1;

extern char *bconftext;
#define yytext_ptr bconftext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up bconftext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	bconfleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[293] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   61,   58,
       55,   57,   57,   58,   58,   58,   58,   34,   31,   31,
       57,   31,   29,   58,   58,   31,   31,   31,   31,   31,
       34,   34,   30,   30,   34,   34,   34,   34,   59,   55,
       60,   50,   59,   59,   38,   59,   37,   55,   35,   60,
       36,   36,    0,    0,   55,    0,   57,   57,   57,    0,
        0,   32,    0,    0,    0,   56,   56,    0,   33,    0,
        0,    0,    0,   34,   34,   31,    0,   57,   31,   28,
       55,   34,   34,   34,   31,   34,   34,    6,   34,    2,
       34,   34,   34,   34,   34,   34,   34,   34,   55,    0,

       39,    0,    0,    0,    0,   48,    0,    0,    0,   40,
       49,   41,   35,   36,   32,    0,    0,   56,   32,    0,
        0,    0,    0,   33,    0,    0,   56,    0,    0,    0,
        0,   31,   34,   34,   34,   31,   34,   34,   34,   34,
       34,   24,   22,   34,   34,   34,   34,   34,   34,   34,
        0,   53,    0,   54,   51,   42,   44,   45,   46,   47,
       43,    0,    0,   56,    0,    0,    0,    0,    0,    0,
       56,    0,    0,    0,    0,   16,   34,   34,   34,   34,
        5,    4,   34,   11,   34,   34,   34,   34,    3,   34,
       34,   52,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,    7,    0,    0,
        0,    0,    0,    0,    0,    0,   27,   34,   34,   34,
       34,   34,   34,   34,   12,    1,   26,   34,   13,   34,
       34,   34,   34,   10,   34,   34,   34,   34,   34,   34,
       34,   19,   34,   34,   34,   17,   34,   34,   34,   34,
       34,   20,   34,   34,   34,   23,   21,   34,   34,   34,
       34,   34,   14,   34,   34,   34,   34,   34,   34,   34,
       18,   34,   34,   25,   34,    9,   34,   34,   34,   15,
        8,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,    1,    1,   10,    1,
        1,    1,    1,    1,   11,   12,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   15,   15,    1,   16,    1,
       17,    1,   18,    1,   19,   19,   19,   19,   19,   19,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       20,   21,   22,    1,   23,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   12,   12,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   12,   44,
       45,   46,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    1,    5,    6,
        7,    8,    9,    9,   10,    1,    1,    6,   11,    1,
        6,    1,    8,   12,   12,   11,   11,   12,   12,    8,
        8,    8,    8,    8,   13,    8,    8,    8,   13,    8,
       13,    8,   13,   13,    8,    8
    } ;

static yyconst flex_int16_t yy_base[316] =
    {   0,
        0,    0,   45,   66,   88,  110,  119,  134, 1183, 1174,
       53,   60,  130,   78,   76,  155,   49,  201,  216, 1126,
      212,  260,  121,   46,  136, 1133,   29, 1115,   67, 1099,
      306,  114,   79, 1102, 1076,  197,  120,  117, 1239,  232,
     1239, 1072,  326,  348, 1239, 1085, 1239,  234,    0, 1073,
     1239, 1072, 1054,  243,  328,  224,  210,  315,  334,  338,
      242, 1028,  344,  392,  317, 1239, 1021,  350,  436,  358,
      238,  382,  456,  500,  995,  932,  510,  366,    0,  967,
      375,  222,  228,   47,  326,  361,  126,  945,  379,  943,
      315,  359,  380,  369,  336,  942,  386,  304,  427,  962,

     1239,    0,  957,  458,  953, 1239,  916,  381,  387,  924,
     1239, 1239,    0, 1239, 1239,  411,  475,  483,  484,  523,
      552,  571,  584,  613,  454,  537,  540,  633,  652,  636,
      684,    0,  224,  398,  339,  919,  411,  176,  913,  485,
      412,  911,  902,  514,  282,  422,  432,  518,  475,  901,
      918, 1239,  917, 1239, 1239, 1239, 1239, 1239, 1239, 1239,
     1239,  550,    0,  455,  711,  730,  671,  756,  650,    0,
      562,  783,  792,  727,  818,  881,  486,  879,  539,  617,
      876,  870,  860,  846,  554,  461,  574,  566,  781,  576,
      597, 1239,  801,  709,  841,  868,  887,  758,    0,  707,

      907,  934,  953,  768,    0,  764,  604,  723,  620,  523,
      577,  633,  699,  639,  698,  598,  504,  677,  662,    0,
      791,    0,  679,    0,  875,    0,  644,  660,  624,  654,
      658,  558,  708,  711,  625,  599,  579,  701,  578,  918,
      674,  725,  760,  561,  773,  541,  774,  505,  739,  762,
      785,  483,  719,  786,  745,  465,  802,  524,  795,  801,
      821,  447,  833,  823,  859,  423,  391,  845,  824,  822,
      856,  797,  370,  858,  869,  360,  807,  877,  676,  875,
      329,  301,  891,  226,  899,  119,  917,   97,  934,   73,
       50, 1239,  982,  995, 1008, 1021, 1034, 1047, 1060, 1073,

     1082, 1089, 1102, 1115, 1128, 1141, 1154, 1167, 1173, 1183,
     1195, 1207, 1217, 1222, 1226
    } ;

static yyconst flex_int16_t yy_def[316] =
    {   0,
      292,    1,  293,  293,  294,  294,  295,  295,  292,  296,
      296,  292,  292,  297,  298,  292,  299,  300,  296,   19,
      296,  292,  296,  296,  296,   22,   22,   22,   22,   22,
      300,   31,   31,   31,   31,   31,   31,   31,  292,  292,
      292,  292,  301,  292,  292,  292,  292,  292,  302,  292,
      292,  292,  296,  298,  296,  296,  292,  292,  292,  297,
      303,  296,  304,  296,  298,  292,  292,  298,  305,  299,
      306,  307,   64,  308,   31,   19,   19,  296,   22,  296,
      292,   31,   31,   31,   22,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,  292,  292,

      292,  309,  310,  292,  310,  292,  292,  292,  292,  292,
      292,  292,  302,  292,  292,  311,  304,  303,  298,  304,
      298,  297,   77,  305,  312,  307,  306,  307,  121,  299,
       77,   77,   31,   31,   31,   22,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
      313,  292,  310,  292,  292,  292,  292,  292,  292,  292,
      292,  303,  314,  303,  304,  298,  297,  297,  306,  315,
      306,  307,  166,  299,  299,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,  292,  313,  303,  303,  304,  304,  297,  168,  306,

      306,  307,  307,  299,  175,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,  303,  195,
      304,  197,  306,  201,  307,  203,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,    0,  292,  292,  292,  292,  292,  292,  292,  292,

      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292
    } ;

static yyconst flex_int16_t yy_nxt[1286] =
    {   0,
       10,   11,   12,   13,   11,   10,   14,   15,   16,   17,
       10,   18,   19,   20,   20,   21,   10,   10,   22,   23,
       24,   25,   18,   22,   26,   27,   28,   29,   30,   18,
       31,   32,   18,   33,   34,   18,   18,   18,   35,   36,
       37,   38,   18,   18,   34,   18,   40,   41,   81,   40,
       42,   43,   71,   54,   55,   44,   72,   55,   62,   83,
       54,   45,   57,   58,   84,   46,   47,   40,   41,   73,
       40,   42,   43,   56,   75,   57,   44,   75,   66,   67,
      135,   61,   45,   68,   62,   63,   46,   47,   41,   48,
       41,   41,   48,   41,   41,   41,   41,   41,   64,   86,

       75,   87,   92,   41,   41,   41,   75,   41,   50,   41,
       41,   48,   41,   41,   48,   41,   41,   41,   41,   41,
       48,   51,   52,   48,  290,   41,   41,   41,   54,   41,
       50,   41,   59,   58,   51,   48,   51,   52,   48,   50,
       80,   75,   90,   54,   75,   57,   75,   75,   91,   51,
       96,   98,  140,   75,   50,   53,   53,   80,   97,   53,
       53,   53,   54,   53,   53,   53,   69,   53,   53,   53,
       53,   53,   53,   69,   53,   53,   53,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,

       69,   53,   53,   75,  181,   53,   53,   53,   54,   53,
       53,   74,   57,   58,   57,   58,   53,   53,   53,   54,
       53,   53,   53,   54,   75,   57,   81,   78,   76,   76,
       76,   54,   94,   99,   76,   99,   99,   95,   99,   76,
       76,   76,   76,   76,   76,   66,   67,  115,  115,   75,
       68,   75,  100,   75,  100,   75,  176,  133,  125,   77,
       53,   53,  116,  134,   53,   53,   53,   54,   53,   53,
       74,   75,   79,   79,   79,   53,   53,   53,   79,   53,
       53,   53,   75,   79,   79,   79,   79,   79,   79,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,

       75,   75,   75,   75,   75,   75,   53,   53,  186,   75,
       53,   53,   53,   54,   53,   53,   74,   59,   58,   66,
       67,   53,   53,   53,   68,   53,   53,   53,  286,   55,
       57,   75,   55,   89,  102,   54,   57,   58,  104,  104,
      104,   61,   75,  150,   62,   63,   66,  118,   56,   57,
      119,  120,   66,   67,  136,  143,   75,   68,   64,  105,
      105,   71,  137,   75,  121,   72,   75,   62,   57,   58,
      105,  106,  178,   54,  147,  107,   99,  108,   73,   99,
      109,   78,  110,  111,   66,  127,   75,  281,   75,  128,
      144,  119,  138,  112,   61,  100,   75,   75,   60,   54,

      139,   60,  129,  145,  122,  122,   75,   75,  157,   60,
      146,  141,   60,   75,  159,   60,   60,  149,   75,   60,
       60,  158,  142,  162,  162,   75,   60,  160,   99,  177,
       60,   99,   60,  180,   60,  123,   53,   53,   75,   75,
       53,   53,   53,   54,   53,   53,   53,  100,  184,   75,
       75,   53,   53,   53,  163,   53,   53,   53,   71,   75,
      187,  115,   70,  188,  154,   70,  169,  169,  130,  130,
      104,  104,  104,   70,   75,  116,   70,   66,  118,   70,
       70,  119,  120,   70,   70,   66,   66,   67,   75,  115,
       70,   68,   75,  214,   70,  121,   70,  170,   70,  131,

       53,   53,   75,  116,   53,   53,   53,   54,   53,   53,
       75,  206,   75,   75,  190,   53,   53,   53,  183,   53,
       53,   53,  132,  132,  132,   66,  118,  238,  132,  119,
      120,   75,  258,  132,  132,  132,  132,  132,  132,   66,
      127,   75,   66,  121,  128,   75,  119,  231,  185,  115,
       75,   75,  189,   53,  164,   67,  115,  129,  117,   68,
      125,  117,  194,  194,  165,  165,   75,  266,  256,  117,
      116,  115,  117,  208,   61,  117,  117,   62,   63,  117,
      117,   75,  125,  167,  167,   75,  117,  213,   75,  243,
      117,   64,  117,   75,  117,  166,  168,  168,  168,  215,

      216,   75,  168,   75,   75,   75,   75,  168,  168,  168,
      168,  168,  168,   53,   53,  232,  217,   53,   53,   53,
       54,   53,   53,   53,   75,   75,   75,  237,   53,   53,
       53,   75,   53,   53,   53,   66,  127,  218,  228,   71,
      128,  209,  119,   72,   75,   62,  240,   75,  174,  174,
      210,   75,   75,  129,  171,  230,   73,  211,  126,  115,
       75,  126,  200,  200,  172,  172,   75,  233,  115,  126,
      125,   75,  126,  235,   61,  126,  126,   62,   63,  126,
      126,   75,  116,  198,  198,   75,  126,   75,  115,  241,
      126,   64,  126,  242,  126,  173,  175,  175,  175,  125,

      239,   75,  175,   75,   75,  284,  252,  175,  175,  175,
      175,  175,  175,   66,  118,  115,  115,  119,  120,  223,
      223,  219,  219,  196,  196,  236,  234,  125,   75,  116,
       71,  121,   66,   67,   72,   75,   62,   68,   75,  204,
      204,  246,  197,  197,  197,  245,   75,   73,  197,  244,
      229,  262,   75,  197,  197,  197,  197,  197,  197,   61,
      253,   61,   62,   63,   62,   63,   75,  264,  199,  199,
      199,   71,   75,  259,  199,   72,   64,   62,   64,  199,
      199,  199,  199,  199,  199,   66,  127,   75,   73,   75,
      128,  227,  119,   66,  118,  202,  202,  119,  120,  254,

       75,   75,  260,  129,  203,  203,  203,  192,   75,  257,
      203,  121,   75,   75,  255,  203,  203,  203,  203,  203,
      203,   71,   75,  261,   75,   72,  263,   62,   75,   75,
      205,  205,  205,  278,   75,  267,  205,  265,   73,  268,
      282,  205,  205,  205,  205,  205,  205,  115,   75,   75,
       75,   75,  269,  220,  220,  220,  270,  271,  272,  220,
       75,  116,  276,  275,  220,  220,  220,  220,  220,  220,
       66,  118,   75,   75,  119,  120,  274,   66,  127,  277,
      221,  221,  128,   75,  119,   75,   75,  212,  121,   66,
      118,  273,  279,  119,  120,  129,   75,   75,  285,  222,

      222,  222,   75,   75,   75,  222,  207,  121,   75,  280,
      222,  222,  222,  222,  222,  222,  115,  283,   75,  224,
      224,  224,  287,  152,  192,  224,   75,  125,  191,   75,
      224,  224,  224,  224,  224,  224,   66,  127,   75,  288,
      182,  128,  247,  119,   75,   75,  225,  225,  248,  249,
      179,  161,  289,  156,  129,   66,  127,  250,  251,  155,
      128,   75,  119,  152,   81,  226,  226,  226,  291,  148,
       75,  226,   75,  129,   54,   53,  226,  226,  226,  226,
      226,  226,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   53,   75,   66,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   60,   54,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       70,   54,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   75,  114,   81,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,  103,   81,  101,  103,
      103,  103,  103,  103,  103,  113,  113,  113,  113,  113,

      113,  113,   61,   93,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  124,   75,
       88,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,   71,   85,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,   74,   82,   53,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
      151,   54,  292,  151,  151,  151,  153,  292,  292,  292,
      153,  153,  153,  153,  153,  153,   61,  292,   61,  292,

       61,  292,  292,   61,  292,  292,   61,   61,   71,  292,
       71,  292,   71,  292,  292,   71,  292,  292,   71,   71,
      193,  292,  292,  292,  193,  193,  193,  193,  193,  193,
      195,  195,  195,  195,  201,  201,  201,  201,    9,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292
    } ;

static yyconst flex_int16_t yy_chk[1286] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,   24,    3,
        3,    3,   17,   24,   11,    3,   17,   11,   17,   27,
       11,    3,   12,   12,   27,    3,    3,    4,    4,   17,
        4,    4,    4,   11,   84,   12,    4,  291,   15,   15,
       84,   14,    4,   15,   14,   14,    4,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,   14,   29,

      290,   29,   33,    5,    5,    5,   33,    5,    5,    5,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        7,    7,    7,    7,  288,    6,    6,    6,   23,    6,
        6,    6,   13,   13,    7,    8,    8,    8,    8,    7,
       23,   32,   32,   25,   38,   13,  286,   37,   32,    8,
       37,   38,   87,   87,    8,   16,   16,   25,   37,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,

       16,   18,   18,  138,  138,   18,   18,   18,   18,   18,
       18,   18,   57,   57,   21,   21,   18,   18,   18,   21,
       18,   18,   18,   19,   36,   57,   56,   21,   19,   19,
       19,   56,   36,   40,   19,   48,   40,   36,   48,   19,
       19,   19,   19,   19,   19,   54,   54,   71,   61,   82,
       54,  133,   40,  284,   48,   83,  133,   82,   71,   19,
       22,   22,   61,   83,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   31,   31,  145,  145,
       31,   31,   31,   31,   31,   31,   31,   58,   58,   65,
       65,   31,   31,   31,   65,   31,   31,   31,  282,   55,
       58,   98,   55,   31,   43,   55,   59,   59,   43,   43,
       43,   60,   91,   98,   60,   60,   63,   63,   55,   59,
       63,   63,   68,   68,   85,   91,  281,   68,   60,   43,
       43,   70,   85,   95,   63,   70,  135,   70,   78,   78,
       43,   44,  135,   78,   95,   44,   81,   44,   70,   81,
       44,   78,   44,   44,   72,   72,   92,  276,   86,   72,
       92,   72,   86,   44,   64,   81,   94,  273,   64,   64,

       86,   64,   72,   93,   64,   64,   89,   93,  108,   64,
       94,   89,   64,   97,  109,   64,   64,   97,  267,   64,
       64,  108,   89,  116,  116,  134,   64,  109,   99,  134,
       64,   99,   64,  137,   64,   64,   69,   69,  137,  141,
       69,   69,   69,   69,   69,   69,   69,   99,  141,  146,
      266,   69,   69,   69,  116,   69,   69,   69,   73,  147,
      146,  164,   73,  147,  104,   73,  125,  125,   73,   73,
      104,  104,  104,   73,  262,  164,   73,  117,  117,   73,
       73,  117,  117,   73,   73,  118,  119,  119,  186,  118,
       73,  119,  256,  186,   73,  117,   73,  125,   73,   73,

       74,   74,  149,  118,   74,   74,   74,   74,   74,   74,
      252,  177,  140,  177,  149,   74,   74,   74,  140,   74,
       74,   74,   77,   77,   77,  120,  120,  217,   77,  120,
      120,  217,  248,   77,   77,   77,   77,   77,   77,  126,
      126,  144,  127,  120,  126,  148,  126,  210,  144,  127,
      210,  258,  148,   77,  121,  121,  162,  126,  121,  121,
      127,  121,  162,  162,  121,  121,  179,  258,  246,  121,
      162,  171,  121,  179,  122,  121,  121,  122,  122,  121,
      121,  185,  171,  122,  122,  232,  121,  185,  244,  232,
      121,  122,  121,  188,  121,  121,  123,  123,  123,  187,

      188,  187,  123,  190,  211,  239,  237,  123,  123,  123,
      123,  123,  123,  124,  124,  211,  190,  124,  124,  124,
      124,  124,  124,  124,  191,  216,  236,  216,  124,  124,
      124,  207,  124,  124,  124,  128,  128,  191,  207,  130,
      128,  180,  128,  130,  180,  130,  229,  209,  130,  130,
      180,  229,  235,  128,  129,  209,  130,  180,  129,  169,
      212,  129,  169,  169,  129,  129,  214,  212,  219,  129,
      169,  227,  129,  214,  167,  129,  129,  167,  167,  129,
      129,  230,  219,  167,  167,  231,  129,  228,  223,  230,
      129,  167,  129,  231,  129,  129,  131,  131,  131,  223,

      228,  241,  131,  279,  218,  279,  241,  131,  131,  131,
      131,  131,  131,  165,  165,  194,  200,  165,  165,  200,
      200,  194,  194,  165,  165,  215,  213,  200,  238,  194,
      174,  165,  166,  166,  174,  233,  174,  166,  234,  174,
      174,  238,  166,  166,  166,  234,  253,  174,  166,  233,
      208,  253,  242,  166,  166,  166,  166,  166,  166,  168,
      242,  198,  168,  168,  198,  198,  249,  255,  168,  168,
      168,  204,  255,  249,  168,  204,  168,  204,  198,  168,
      168,  168,  168,  168,  168,  172,  172,  243,  204,  250,
      172,  206,  172,  221,  221,  172,  172,  221,  221,  243,

      245,  247,  250,  172,  173,  173,  173,  193,  189,  247,
      173,  221,  251,  254,  245,  173,  173,  173,  173,  173,
      173,  175,  259,  251,  272,  175,  254,  175,  260,  257,
      175,  175,  175,  272,  277,  259,  175,  257,  175,  260,
      277,  175,  175,  175,  175,  175,  175,  195,  261,  270,
      264,  269,  261,  195,  195,  195,  263,  264,  264,  195,
      263,  195,  270,  269,  195,  195,  195,  195,  195,  195,
      196,  196,  268,  184,  196,  196,  268,  225,  225,  271,
      196,  196,  225,  271,  225,  274,  265,  183,  196,  197,
      197,  265,  274,  197,  197,  225,  275,  182,  280,  197,

      197,  197,  280,  181,  278,  197,  178,  197,  176,  275,
      197,  197,  197,  197,  197,  197,  201,  278,  283,  201,
      201,  201,  283,  153,  151,  201,  285,  201,  150,  143,
      201,  201,  201,  201,  201,  201,  202,  202,  142,  285,
      139,  202,  240,  202,  287,  240,  202,  202,  240,  240,
      136,  110,  287,  107,  202,  203,  203,  240,  240,  105,
      203,  289,  203,  103,  100,  203,  203,  203,  289,   96,
       90,  203,   88,  203,   80,   76,  203,  203,  203,  203,
      203,  203,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  294,  294,  294,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  294,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  296,   75,   67,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  297,   62,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      299,   53,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  300,   52,   50,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  301,   46,   42,  301,
      301,  301,  301,  301,  301,  302,  302,  302,  302,  302,

      302,  302,  303,   35,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  305,   34,
       30,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  306,   28,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  308,   26,   20,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      309,   10,    9,  309,  309,  309,  310,    0,    0,    0,
      310,  310,  310,  310,  310,  310,  311,    0,  311,    0,

      311,    0,    0,  311,    0,    0,  311,  311,  312,    0,
      312,    0,  312,    0,    0,  312,    0,    0,  312,  312,
      313,    0,    0,    0,  313,  313,  313,  313,  313,  313,
      314,  314,  314,  314,  315,  315,  315,  315,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[61] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 
    0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int bconf_flex_debug;
int bconf_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *bconftext;
#line 1 "bconf.l"
#line 6 "bconf.l"
#define MAX_SOURCE_DEPTH 20

struct source_file {
  YY_BUFFER_STATE buffer;
  char *name;
  int lineno;
};

static struct source_file source_stack[MAX_SOURCE_DEPTH];
static int source_index = 0;

extern char *filename;
/* Tristate constants */
/* Strings */
/* Whitespace and newlines */
/* Bash-style comments */
/* separate lexing for test conditions */

/* include other config files */


#line 906 "bconf.lex.c"

#define INITIAL 0
#define IN_TEST 1
#define IN_SOURCE 2
#define OPEN_SOURCE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int bconflex_destroy (void );

int bconfget_debug (void );

void bconfset_debug (int debug_flag  );

YY_EXTRA_TYPE bconfget_extra (void );

void bconfset_extra (YY_EXTRA_TYPE user_defined  );

FILE *bconfget_in (void );

void bconfset_in  (FILE * in_str  );

FILE *bconfget_out (void );

void bconfset_out  (FILE * out_str  );

int bconfget_leng (void );

char *bconfget_text (void );

int bconfget_lineno (void );

void bconfset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int bconfwrap (void );
#else
extern int bconfwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( bconftext, bconfleng, 1, bconfout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( bconfin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( bconfin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, bconfin))==0 && ferror(bconfin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(bconfin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int bconflex (void);

#define YY_DECL int bconflex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after bconftext and bconfleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 52 "bconf.l"


#line 1099 "bconf.lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! bconfin )
			bconfin = stdin;

		if ( ! bconfout )
			bconfout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			bconfensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				bconf_create_buffer(bconfin,YY_BUF_SIZE );
		}

		bconf_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of bconftext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 293 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1239 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < bconfleng; ++yyl )
				if ( bconftext[yyl] == '\n' )
					   
    bconflineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 55 "bconf.l"
BEGIN(IN_SOURCE);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 57 "bconf.l"
return IF;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 58 "bconf.l"
return THEN;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 59 "bconf.l"
return ELSE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 60 "bconf.l"
return ELIF;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 61 "bconf.l"
return FI;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 62 "bconf.l"
return UNSET;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "bconf.l"
return MAINMENU_OPTION;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 65 "bconf.l"
return MAINMENU_NAME;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 66 "bconf.l"
return ENDMENU;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "bconf.l"
return HELP;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 68 "bconf.l"
return READLN;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 69 "bconf.l"
return COMMENT;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "bconf.l"
return DEFINE_BOOL;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "bconf.l"
return DEFINE_TRISTATE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "bconf.l"
return BOOL;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 73 "bconf.l"
return TRISTATE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 74 "bconf.l"
return DEP_TRISTATE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 75 "bconf.l"
return DEP_BOOL;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 76 "bconf.l"
return DEP_MBOOL;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 77 "bconf.l"
return DEFINE_INT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "bconf.l"
return INT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 79 "bconf.l"
return DEFINE_HEX;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 80 "bconf.l"
return HEX;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 81 "bconf.l"
return DEFINE_STRING;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 82 "bconf.l"
return STRING;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 83 "bconf.l"
return CHOICE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 85 "bconf.l"
{ fprintf(stderr, "error:%s:%d: \"%s\"ksh-style conditionals unsupported\n", filename, bconflineno, bconftext); exit(1); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 87 "bconf.l"
BEGIN(IN_TEST);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 "bconf.l"
{
  switch (bconftext[0]) {
  case 'y': yylval.string = "y"; break;
  case 'n': yylval.string = "n"; break;
  case 'm': yylval.string = "m"; break;
  default:
    fprintf(stderr, "lexer error:%s:%d: incorrect tristate const\n", \
            filename, bconflineno);
    break;
  }

  return TRISTATE_CONST;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 103 "bconf.l"
{
  yylval.string = malloc(sizeof(char) * (strlen(bconftext) + 1));
  strncpy(yylval.string, bconftext, strlen(bconftext) + 1);
  return NUMBER;
}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 109 "bconf.l"
{
  char *c;
  bconftext[bconfleng-1] = '\0'; bconftext += 1;
  yylval.string = malloc(sizeof(char) * (strlen(bconftext) + 1));
  strncpy(yylval.string, bconftext, strlen(bconftext) + 1);
  for (c = yylval.string; *c != '\0'; c++) {
    if (*c == '\\' && *(c + 1) == '\n') {
      *c = ' ';
      *(c+1) = ' ';
    }
  }
  return STRING_CONST;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 123 "bconf.l"
{
  bconftext += 1;
  yylval.string = malloc(sizeof(char) * (strlen(bconftext) + 1));
  strncpy(yylval.string, bconftext, strlen(bconftext) + 1);
  return CONFIG_VAR;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 130 "bconf.l"
{
  yylval.string = malloc(sizeof(char) * (strlen(bconftext) + 1));
  strncpy(yylval.string, bconftext, strlen(bconftext) + 1);
  return WORD;
}
	YY_BREAK


case 35:
YY_RULE_SETUP
#line 138 "bconf.l"
{
  if (source_index >= MAX_SOURCE_DEPTH) {
    fprintf(stderr, "fatal error: maximum depth of source includes, %d, "
            "reached.  Set the\nMAX_SOURCE_DEPTH macro to a bigger value.\n",
            MAX_SOURCE_DEPTH);
    exit(1);
  }
  source_stack[source_index].buffer = YY_CURRENT_BUFFER;
  source_stack[source_index].name = filename;
  source_stack[source_index].lineno = bconflineno;
  source_index++;
  filename = malloc(sizeof(char) * (strlen(bconftext) + 1));
  strncpy(filename, bconftext, strlen(bconftext) + 1);
  BEGIN(OPEN_SOURCE);
}
	YY_BREAK


case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 156 "bconf.l"
{
  bconfin = fopen(filename, "r");
  if (!bconfin) {
    fprintf(stderr, "lexer error:%s:%d: file not found, \"%s\"\n",
            source_stack[source_index - 1].name, bconflineno, filename);
    exit(1);
  }
  bconf_switch_to_buffer(bconf_create_buffer(bconfin,YY_BUF_SIZE));
  bconflineno = 1;
  BEGIN(INITIAL);
#ifdef TRACE_LEXER
  fprintf(stderr, "trace:%s:%d: entering %s, depth %d\n", source_stack[source_index-1].name, bconflineno, filename, source_index);
#endif //TRACE_LEXER
}
	YY_BREAK

case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_TEST):
case YY_STATE_EOF(IN_SOURCE):
case YY_STATE_EOF(OPEN_SOURCE):
#line 172 "bconf.l"
{
#ifdef TRACE_LEXER
fprintf(stderr, "trace:%s:%d: leaving\n", filename, bconflineno);
#endif //TRACE_LEXER
if (--source_index < 0) {
  yyterminate();
} else {
  bconf_delete_buffer(YY_CURRENT_BUFFER);
  bconf_switch_to_buffer(source_stack[source_index].buffer);
  free(filename);
  filename = source_stack[source_index].name;
  bconflineno = source_stack[source_index].lineno + 1;  // plus one for the "source filename\n" command
}
}
	YY_BREAK

case 37:
YY_RULE_SETUP
#line 188 "bconf.l"
BEGIN(INITIAL);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 189 "bconf.l"
return TEST_STREQ;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 190 "bconf.l"
return TEST_STRNE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 191 "bconf.l"
return TEST_N;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 192 "bconf.l"
return TEST_Z;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 193 "bconf.l"
return TEST_EQ;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 194 "bconf.l"
return TEST_NE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 195 "bconf.l"
return TEST_GE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 196 "bconf.l"
return TEST_GT;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 197 "bconf.l"
return TEST_LE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 198 "bconf.l"
return TEST_LT;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 199 "bconf.l"
return TEST_AND;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 200 "bconf.l"
return TEST_OR;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 201 "bconf.l"
return TEST_BANG;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 202 "bconf.l"
{
  bconftext[bconfleng-1] = '\0'; bconftext += 1;
  switch (bconftext[0]) {
  case 'y': yylval.string = "y"; break;
  case 'n': yylval.string = "n"; break;
  case 'm': yylval.string = "m"; break;
  default:
    fprintf(stderr, "lexer error:%s:%d: incorrect tristate const\n", \
            filename, bconflineno);
    break;
  }
  return TRISTATE_CONST;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 215 "bconf.l"
{
  bconftext[bconfleng-1] = '\0'; bconftext += 2;
  yylval.string = malloc(sizeof(char) * (strlen(bconftext) + 1));
  strncpy(yylval.string, bconftext, strlen(bconftext) + 1);
  return CONFIG_VAR;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 221 "bconf.l"
{
  bconftext[bconfleng-1] = '\0'; bconftext += 2;
  yylval.string = malloc(sizeof(char) * (strlen(bconftext) + 1));
  strncpy(yylval.string, bconftext, strlen(bconftext) + 1);
  return STRING_CONST;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 227 "bconf.l"
{
  bconftext[bconfleng-1] = '\0'; bconftext += 1;
  yylval.string = malloc(sizeof(char) * (strlen(bconftext) + 1));
  strncpy(yylval.string, bconftext, strlen(bconftext) + 1);
  return NUMBER;
}
	YY_BREAK


case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 236 "bconf.l"

	YY_BREAK


case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 240 "bconf.l"

	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 241 "bconf.l"
return NEWLINE;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 242 "bconf.l"
{ fprintf(stderr, "lexer error:%s:%d: %s\n", filename, bconflineno, bconftext); exit(1); }
	YY_BREAK


case 59:
YY_RULE_SETUP
#line 246 "bconf.l"
{ fprintf(stderr, "lexer error:%s:%d: %s\n", filename, bconflineno, bconftext); exit(1); }
	YY_BREAK

case 60:
YY_RULE_SETUP
#line 248 "bconf.l"
ECHO;
	YY_BREAK
#line 1621 "bconf.lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed bconfin at a new source and called
			 * bconflex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = bconfin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( bconfwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * bconftext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of bconflex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					bconfrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			bconfrestart(bconfin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) bconfrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 293 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 293 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 292);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up bconftext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --bconflineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					bconfrestart(bconfin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( bconfwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve bconftext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    bconflineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void bconfrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        bconfensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            bconf_create_buffer(bconfin,YY_BUF_SIZE );
	}

	bconf_init_buffer(YY_CURRENT_BUFFER,input_file );
	bconf_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void bconf_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		bconfpop_buffer_state();
	 *		bconfpush_buffer_state(new_buffer);
     */
	bconfensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	bconf_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (bconfwrap()) processing, but the only time this flag
	 * is looked at is after bconfwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void bconf_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	bconfin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE bconf_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) bconfalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in bconf_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) bconfalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in bconf_create_buffer()" );

	b->yy_is_our_buffer = 1;

	bconf_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with bconf_create_buffer()
 * 
 */
    void bconf_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		bconffree((void *) b->yy_ch_buf  );

	bconffree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a bconfrestart() or at EOF.
 */
    static void bconf_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	bconf_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then bconf_init_buffer was _probably_
     * called from bconfrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void bconf_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		bconf_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void bconfpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	bconfensure_buffer_stack();

	/* This block is copied from bconf_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from bconf_switch_to_buffer. */
	bconf_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void bconfpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	bconf_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		bconf_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void bconfensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)bconfalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in bconfensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)bconfrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in bconfensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE bconf_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) bconfalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in bconf_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	bconf_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to bconflex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       bconf_scan_bytes() instead.
 */
YY_BUFFER_STATE bconf_scan_string (yyconst char * yystr )
{
    
	return bconf_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to bconflex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE bconf_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) bconfalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in bconf_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = bconf_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in bconf_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up bconftext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		bconftext[bconfleng] = (yy_hold_char); \
		(yy_c_buf_p) = bconftext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		bconfleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int bconfget_lineno  (void)
{
        
    return bconflineno;
}

/** Get the input stream.
 * 
 */
FILE *bconfget_in  (void)
{
        return bconfin;
}

/** Get the output stream.
 * 
 */
FILE *bconfget_out  (void)
{
        return bconfout;
}

/** Get the length of the current token.
 * 
 */
int bconfget_leng  (void)
{
        return bconfleng;
}

/** Get the current token.
 * 
 */

char *bconfget_text  (void)
{
        return bconftext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void bconfset_lineno (int  line_number )
{
    
    bconflineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see bconf_switch_to_buffer
 */
void bconfset_in (FILE *  in_str )
{
        bconfin = in_str ;
}

void bconfset_out (FILE *  out_str )
{
        bconfout = out_str ;
}

int bconfget_debug  (void)
{
        return bconf_flex_debug;
}

void bconfset_debug (int  bdebug )
{
        bconf_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from bconflex_destroy(), so don't allocate here.
     */

    /* We do not touch bconflineno unless the option is enabled. */
    bconflineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    bconfin = stdin;
    bconfout = stdout;
#else
    bconfin = (FILE *) 0;
    bconfout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * bconflex_init()
     */
    return 0;
}

/* bconflex_destroy is for both reentrant and non-reentrant scanners. */
int bconflex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		bconf_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		bconfpop_buffer_state();
	}

	/* Destroy the stack itself. */
	bconffree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * bconflex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *bconfalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *bconfrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void bconffree (void * ptr )
{
	free( (char *) ptr );	/* see bconfrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 248 "bconf.l"
